import 'package:sqflite/sqflite.dart';

const documentGrammarDefaults = <Map<String, Object>>[
  {
    "masterType": "Why Removing",
    "value": "Dangerous tree/branch",
    "code": "DANGER",
    "parentCode": "",
    "displayOrder": 1,
    "kannadaName": "ಅಪಾಯ ಉಂಟಾಗುತ್ತಿರುವ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Why Removing",
    "value": "Development work",
    "code": "WORKS",
    "parentCode": "",
    "displayOrder": 2,
    "kannadaName": "ಅಡಚಣೆ ಉಂಟಾಗುತ್ತಿರುವ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Why Removing",
    "value": "Road widening",
    "code": "WIDEN",
    "parentCode": "",
    "displayOrder": 3,
    "kannadaName": "ಅಡಚಣೆ ಉಂಟಾಗುತ್ತಿರುವ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Why Removing",
    "value": "Repair work",
    "code": "REPAIR",
    "parentCode": "",
    "displayOrder": 4,
    "kannadaName": "ಅಡಚಣೆ ಉಂಟಾಗುತ್ತಿರುವ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Why Removing",
    "value": "Damage to property",
    "code": "DAMAGE",
    "parentCode": "",
    "displayOrder": 5,
    "kannadaName": "ಹಾನಿ ಉಂಟಾಗುತ್ತಿರುವ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Purpose",
    "value": "Safety",
    "code": "GRAMMAR_SAFETY",
    "parentCode": "DANGER",
    "displayOrder": 1,
    "kannadaName": "ಸುರಕ್ಷತೆಗೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Purpose",
    "value": "Construction",
    "code": "GRAMMAR_CONSTRUCTION",
    "parentCode": "WORKS",
    "displayOrder": 2,
    "kannadaName": "ನಿರ್ಮಾಣ ಕಾಮಗಾರಿಗೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Purpose",
    "value": "Widening",
    "code": "GRAMMAR_WIDENING",
    "parentCode": "WIDEN",
    "displayOrder": 3,
    "kannadaName": "ಅಗಲೀಕರಣ ಕಾಮಗಾರಿಗೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Purpose",
    "value": "Repair",
    "code": "GRAMMAR_REPAIR",
    "parentCode": "REPAIR",
    "displayOrder": 4,
    "kannadaName": "ದುರಸ್ತಿ ಕಾಮಗಾರಿಗೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Purpose",
    "value": "Protection",
    "code": "GRAMMAR_PROTECTION",
    "parentCode": "DAMAGE",
    "displayOrder": 5,
    "kannadaName": "ರಕ್ಷಣೆಗೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Structure Type",
    "value": "Building",
    "code": "GRAMMAR_BUILDING",
    "parentCode": "",
    "displayOrder": 1,
    "kannadaName": "ಕಟ್ಟಡ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Structure Type",
    "value": "Road",
    "code": "GRAMMAR_ROAD",
    "parentCode": "",
    "displayOrder": 2,
    "kannadaName": "ರಸ್ತೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Structure Type",
    "value": "Drain",
    "code": "GRAMMAR_DRAIN",
    "parentCode": "",
    "displayOrder": 3,
    "kannadaName": "ಚರಂಡಿ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Structure Type",
    "value": "Bridge",
    "code": "GRAMMAR_BRIDGE",
    "parentCode": "",
    "displayOrder": 4,
    "kannadaName": "ಸೇತುವೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
  {
    "masterType": "Structure Type",
    "value": "Compound wall",
    "code": "GRAMMAR_COMPOUND",
    "parentCode": "",
    "displayOrder": 5,
    "kannadaName": "ಕಾಂಪೌಂಡ್ ಗೋಡೆ",
    "remarks": "GRAMMAR_DEFAULT_20261006",
    "isActive": 1,
  },
];

Future<void> seedDocumentGrammarDefaults(DatabaseExecutor db) async {
  await db.rawUpdate(
    '''update master_data set isActive=0 where ((masterType='Why Removing' and value in ('Dangerous tree/branch','Self convenience','Development work','Financial benefit')) or (masterType='Purpose' and value in ('House Construction','Agriculture','Road Widening','Safety')) or (masterType='Structure Type' and value in ('Building','Road','Layout'))) and coalesce(remarks,'') <> 'GRAMMAR_DEFAULT_20261006'
''',
  );
  for (final row in documentGrammarDefaults) {
    final existing = await db.query(
      'master_data',
      columns: ['id'],
      where: 'masterType=? AND code=? AND remarks=?',
      whereArgs: [row['masterType'], row['code'], row['remarks']],
      limit: 1,
    );
    if (existing.isEmpty) await db.insert('master_data', row);
  }
}
