// Source: Seigniorage Rates 01.01.2026–31.12.2027, PDF pages 3–8, serials 1–123.
// Column 5 -> value; 4 -> scientificName; 3 -> kannadaName; 8 -> rate.
// Source spellings are retained. Blank local names 43/98 use the scientific name.
// Category is intentionally blank. RFO edits remain possible after initialization.
const timberSpeciesDefaults = <Map<String, Object?>>[
  {
    "masterType": "Species",
    "value": "Beete, Beeti",
    "scientificName": "Dalbergia latifolia",
    "kannadaName": "ಬೀಟೆ, ಬೀಟಿ",
    "ratePerCubicMeter": 113463,
    "category": "",
    "displayOrder": 1,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_001",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Saguvani, Thega, Teak",
    "scientificName": "Tectona grandis",
    "kannadaName": "ಸಾಗುವಾನಿ, ತೇಗ, ಟೀಕ್",
    "ratePerCubicMeter": 115125,
    "category": "",
    "displayOrder": 2,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_002",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Ebony, Karimara",
    "scientificName": "Diospyros ebenum",
    "kannadaName": "ಎಬೋನಿ, ಕರಿಮರ",
    "ratePerCubicMeter": 91360,
    "category": "",
    "displayOrder": 3,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_003",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Honne, Bijasal, Venugai, Vengal",
    "scientificName": "Pterocarpus marsupium",
    "kannadaName": "ಹೊನ್ನೆ, ಬಿಜಸಾಲ, ವೆಣುಗೈ, ವೆಂಗಲ್",
    "ratePerCubicMeter": 34732,
    "category": "",
    "displayOrder": 4,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_004",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Hebbalasu, Aini, Angili",
    "scientificName": "Artocarpus hirsuta",
    "kannadaName": "ಹೆಬ್ಬಲಸು, ಐನಿ, ಆಂಗಿಲಿ",
    "ratePerCubicMeter": 24161,
    "category": "",
    "displayOrder": 5,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_005",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Hadaga",
    "scientificName": "Cordia macleodii",
    "kannadaName": "ಹಡಗ, ಬಿಳಿ ಚಲ್ಲೆ, ಹದಂಗ",
    "ratePerCubicMeter": 22953,
    "category": "",
    "displayOrder": 6,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_006",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "White Cedar, Bilidevadari, Vellangi, Devagarige",
    "scientificName": "Dysoxylum malabaricum",
    "kannadaName": "ವೈಟ್ ಸೀಡರ್, ಬಿಳಿ ದೇವದಾರಿ, ವೆಲ್ಲಂಗಿ, ದೇವಗರಿಗೆ",
    "ratePerCubicMeter": 78524,
    "category": "",
    "displayOrder": 7,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_007",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kiralbogi, Boga",
    "scientificName": "Hopea parviflora",
    "kannadaName": "ಕಿರಾಲಬೋಗಿ, ಬೋಗ",
    "ratePerCubicMeter": 21292,
    "category": "",
    "displayOrder": 8,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_008",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Nandi, Benteak, Nana",
    "scientificName": "Lagerstroemia lanceolata",
    "kannadaName": "ನಂದಿ, ಬೆಂಟೀಕ್, ನಾನಾ",
    "ratePerCubicMeter": 24916,
    "category": "",
    "displayOrder": 9,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_009",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Nagasampige, Atta, Nagakesara, Nangal",
    "scientificName": "Mesua ferrea",
    "kannadaName": "ನಾಗಸಂಪಿಗೆ, ಅಟ್ಟಾ, ನಾಗಕೇಸರಿ, ನಂಗಲ್",
    "ratePerCubicMeter": 15856,
    "category": "",
    "displayOrder": 10,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_010",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Betta-honne, Karimuttal",
    "scientificName": "Ougenia dalbergioides",
    "kannadaName": "ಬೆಟ್ಟ ಹೊನ್ನೆ, ಕರಿಮುತ್ತಾಲ್, ಕರಿ ಹೊನ್ನೆ",
    "ratePerCubicMeter": 24161,
    "category": "",
    "displayOrder": 11,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_011",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Mathi, Nalamaddi, Laurel",
    "scientificName": "Terminalia tomentosa/elliptica",
    "kannadaName": "ಮತ್ತಿ, ನಳಮಡ್ಡಿ, ಲಾರೆಲ್",
    "ratePerCubicMeter": 19631,
    "category": "",
    "displayOrder": 12,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_012",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Balanji",
    "scientificName": "Acrocarpus fraxinifolius",
    "kannadaName": "ಬಳಂಜಿ",
    "ratePerCubicMeter": 10269,
    "category": "",
    "displayOrder": 13,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_013",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Haldu, Yethiga, Heddi",
    "scientificName": "Adina cordifolia",
    "kannadaName": "ಹಳ್ದು, ಯತ್ತಿಗಾ, ಹೆಡ್ಡಿ, ಅನವು",
    "ratePerCubicMeter": 19631,
    "category": "",
    "displayOrder": 14,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_014",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bage, Kekke, Dilisana",
    "scientificName": "Albizzia lebbek",
    "kannadaName": "ಬಾಗೆ, ಕೆಕ್ಕೆ, ದಿಲಿಸನಾ, ಸಿರಿಸಲ",
    "ratePerCubicMeter": 22651,
    "category": "",
    "displayOrder": 15,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_015",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bilwara, Kalasiris",
    "scientificName": "Albizzia odoratissima",
    "kannadaName": "ಬಿಲ್ವಾರಾ, ಕಲಸಿರಿಸ್, ಶಿರಿಕಾ",
    "ratePerCubicMeter": 22651,
    "category": "",
    "displayOrder": 16,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_016",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Atta",
    "scientificName": "Neolarmarckia cadamba",
    "kannadaName": "ಅಟ್ಟಾ, ಕದಂಬ, ಕಡಬೆ",
    "ratePerCubicMeter": 7550,
    "category": "",
    "displayOrder": 17,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_017",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Beng (large flowered and capsulated silk cotton)",
    "scientificName": "Bombax insigne",
    "kannadaName": "ಬೆಂಗ್ (ದೊಡ್ಡ ಹೂವಾಗಿ ಮತ್ತು ರೇಷ್ಮೆ ಹತ್ತಿಯ ಪೊರೆ)",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 18,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_018",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Poon, Surohonne",
    "scientificName": "Calophyllum tomentosum",
    "kannadaName": "ಪೂನ್ ಸುರುಹೊನ್ನೆ",
    "ratePerCubicMeter": 11346,
    "category": "",
    "displayOrder": 19,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_019",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Gurjan, Kalpine",
    "scientificName": "Dipterocarpus indicus",
    "kannadaName": "ಗುರ್ಜನ್, ಕಾಲ್ಪೈನ್, ಬನಸಂಪ, ಚಲ್ಲೆನ್ಸ್",
    "ratePerCubicMeter": 11326,
    "category": "",
    "displayOrder": 20,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_020",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bikki, Guddarong, Dundate",
    "scientificName": "Elaeocarpus oblongus (Syn. E. Serratus)",
    "kannadaName": "ಬಿಕ್ಕಿ, ಗುಡ್ಡರೊಂಗ್, ದುಂಡಟೆ, ಬೀಜದಮರ, ಅಡಕುಂಜಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 21,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_021",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Makali, Mankali, Chattuva, Aspin",
    "scientificName": "Evodia roxburghiana",
    "kannadaName": "ಮಾಕಳಿ, ಮಂಕಳಿ, ಚಟ್ಟುವ, ಆಸ್ಪಿನ್, ಮುಗಳಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 22,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_022",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Massi",
    "scientificName": "Litsea zeylanica",
    "kannadaName": "ಮಸ್ಸಿ, ಬಿಳಿಸಿಸಂಗಿ",
    "ratePerCubicMeter": 28541,
    "category": "",
    "displayOrder": 23,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_023",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Jalari, Bilibevu",
    "scientificName": "Shorea talura",
    "kannadaName": "ಜಲರಿ, ಬಿಳಿಬೇವು, ಅರಗಿನ ಮರ",
    "ratePerCubicMeter": 12534,
    "category": "",
    "displayOrder": 24,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_024",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kalam, Kadaval, Phaldu",
    "scientificName": "Mitragyna parviflora",
    "kannadaName": "ಕಲಂ, ಕಡವಳ್, ಫಾಲ್ಡು, ನೀರ ಕದಂಬ, ಸಣ್ಣ",
    "ratePerCubicMeter": 11326,
    "category": "",
    "displayOrder": 25,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_025",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Chunga",
    "scientificName": "Symplocos spicata",
    "kannadaName": "ಚಂಗ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 26,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_026",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Red cedar, Laldevadari, Noga",
    "scientificName": "Toona ciliata",
    "kannadaName": "ರೆಡ್ ಸಿಡಾರ್, ಲಾಲದೇವದಾರಿ, ನೋಗ, ಗಂಧಗರಿಗೆ",
    "ratePerCubicMeter": 12836,
    "category": "",
    "displayOrder": 27,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_027",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Saldhupa",
    "scientificName": "Vateria indica",
    "kannadaName": "ಸಾಲ್ಧೂಪಾ, ಬಿಳಿಧೂಪ, ಧೂಪದ ಮರ",
    "ratePerCubicMeter": 11326,
    "category": "",
    "displayOrder": 28,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_028",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Halasu, Jack fruit, Fanas",
    "scientificName": "Artocarpus integrifolia",
    "kannadaName": "ಹಲಸು, ಜಾಕ್ ಫ್ರೂಟ್, ಫನಾಸ್",
    "ratePerCubicMeter": 32467,
    "category": "",
    "displayOrder": 29,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_029",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Holehonne, Bobbi",
    "scientificName": "Calophyllum wightianum",
    "kannadaName": "ಹೊಳೆಹೊನ್ನೆ, ಬೊಬ್ಬಿ",
    "ratePerCubicMeter": 9816,
    "category": "",
    "displayOrder": 30,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_030",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kalgarige, Devala, Chukrassia, Indian Mahagony",
    "scientificName": "Chukrassia tabularis",
    "kannadaName": "ಕಲ್‌ಗರಿಗೆ, ದೇವಾಳ, ಚುಕ್ರಸ್ಸಿಯಾ, ಇಂಡಿಯನ್ ಮಹಾಗನಿ",
    "ratePerCubicMeter": 11326,
    "category": "",
    "displayOrder": 31,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_031",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Jamun, Nerale",
    "scientificName": "Syzygium cumini",
    "kannadaName": "ಜಮುನ, ನೇರಳೆ",
    "ratePerCubicMeter": 12081,
    "category": "",
    "displayOrder": 32,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_032",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Shivane, Gumanadi, Ghamertak",
    "scientificName": "Gmelina arborea",
    "kannadaName": "ಶಿವನೆ, ಗುಮಸಾದಿ, ಗಮೇರ್ತಕ್, ಗಮಾರಿ",
    "ratePerCubicMeter": 22651,
    "category": "",
    "displayOrder": 33,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_033",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Dhaman, Toda, Thadsal, Thadachi",
    "scientificName": "Grewia tiliaefolia",
    "kannadaName": "ಧಾಮನ್, ತೋಡಾ, ತ್ವೆಲ್, ತಡಚಿ",
    "ratePerCubicMeter": 14346,
    "category": "",
    "displayOrder": 34,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_034",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kamara, Yeppi, Anjan, Karachi",
    "scientificName": "Hardwickia binata",
    "kannadaName": "ಕಮರಾ, ಯರಪ್ಪಿ, ಅಂಜನ್ ಕರಾಚಿ",
    "ratePerCubicMeter": 9665,
    "category": "",
    "displayOrder": 35,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_035",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Banata, Balapale",
    "scientificName": "Lopopetalum wightianum",
    "kannadaName": "ಬನಾಟ, ಬಲಪಲೆ",
    "ratePerCubicMeter": 9816,
    "category": "",
    "displayOrder": 36,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_036",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Mahuva, Mohwam, Dodda ippe",
    "scientificName": "Madhuca longifolia",
    "kannadaName": "ಮುಹುವಾ, ಮೊಹ್ವಾಮ್, ದೊಡ್ಡ ಇಪ್ಪೆ, ಕಾಡು ಇಪ್ಪೆ",
    "ratePerCubicMeter": 9362,
    "category": "",
    "displayOrder": 37,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_037",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bankula, Nanje, Ranja",
    "scientificName": "Mimusops elengi",
    "kannadaName": "ಬಕುಲಾ, ನಂಜಿ, ರಂಜ",
    "ratePerCubicMeter": 15856,
    "category": "",
    "displayOrder": 38,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_038",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Hunase, Imli, Amli",
    "scientificName": "Tamarindus indica",
    "kannadaName": "ಹುಣಸೆ, ಇಮ್ಲಿ, ಅಮ್ಲಿ",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 39,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_039",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kindal, Hunal, Hulvev, Pillamardu",
    "scientificName": "Terminalia paniculata",
    "kannadaName": "ಕಿಂಡಲ್, ಹುನಾಲ್, ಹುಲ್ವೆನ್, ಪಿಲ್ಲಾಮರ್ಡು, ಹೊನಗಲು ಮರ",
    "ratePerCubicMeter": 17366,
    "category": "",
    "displayOrder": 40,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_040",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Baranagi, Naviladi",
    "scientificName": "Vitex altissima",
    "kannadaName": "ಬರನಗಿ, ನವಿಲಾಡಿ, ಭರಣಿಗೆ",
    "ratePerCubicMeter": 26728,
    "category": "",
    "displayOrder": 41,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_041",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Jambe",
    "scientificName": "Xylia xylocarpa",
    "kannadaName": "ಜಂಬೆ, ಅರಸು, ತೇಗ",
    "ratePerCubicMeter": 18121,
    "category": "",
    "displayOrder": 42,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_042",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Acacia spp. (excluding A. nilotica and A. catechu)",
    "scientificName": "Acacia spp. (excluding A. nilotica and A. catechu)",
    "kannadaName": "ಜಾಲಿಮರ",
    "ratePerCubicMeter": 15101,
    "category": "",
    "displayOrder": 43,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_043",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Dodamara",
    "scientificName": "Ailanthus excelsa",
    "kannadaName": "ದೊಡ್ಡಮರ",
    "ratePerCubicMeter": 9362,
    "category": "",
    "displayOrder": 44,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_044",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bellata, Safedairial",
    "scientificName": "Albizzia procera",
    "kannadaName": "ಬೆಲ್ಲಟಿ, ಸಫೆದ್ಫರಿಯಲ್, ಬೆಲಾರಿ",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 45,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_045",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Phadus",
    "scientificName": "Alseodaphne semicarpifolia",
    "kannadaName": "ಫಾಡಸ್, ನೆಲ್ವಾರೆ",
    "ratePerCubicMeter": 9967,
    "category": "",
    "displayOrder": 46,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_046",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Satwin, Kadusali, Maddale",
    "scientificName": "Alstonia scholaris",
    "kannadaName": "ದೊಡ್ಡಮಲ, ಹಾಲೆ:ಸಾತ್ವಿನ್, ಕಾಡುಸಾಲಿ, ಮದ್ದಳೆ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 47,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_047",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Dindal, Dindiga, Vellangi",
    "scientificName": "Anogeissus latifolia",
    "kannadaName": "ದಿಂಡಲ್, ದಿಂಡಿಗ, ವೆಲ್ಲಂಗಿ",
    "ratePerCubicMeter": 11930,
    "category": "",
    "displayOrder": 48,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_048",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Wonte, Watehuli",
    "scientificName": "Artocarpus lakoocha",
    "kannadaName": "ವೊಂಟೆ, ವಾಟೆಹುಳಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 49,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_049",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Booruga, Simal, Silk, Cotton",
    "scientificName": "Bombax ceiba",
    "kannadaName": "ಕೆಂಪುಬೂರಗ, ಸಿಮಾಲ್, ಸಿಲ್ಕ್, ಹತ್ತಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 50,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_050",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Salai, Anduk, Sambrani",
    "scientificName": "Boswellia serrata",
    "kannadaName": "ಗುಗ್ಗುಳ ಮರ, ಸಲಾಯ್, ಅಂಡುಕ್, ಸಾಮ್ರಾಣಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 51,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_051",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Goji, Kavarde",
    "scientificName": "Bridelia retusa",
    "kannadaName": "ಆಸನ, ಗುಜ್ಜು, ಕೋಮಂಚಿ, ಮುಳ್ಳುಹೊನ್ನೆ, ಗೋಡಿ, ಕವರ್ಡೆ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 52,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_052",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kaidhupa, Bandapaini",
    "scientificName": "Canarium strictum",
    "kannadaName": "ಕೈಧೂಪ, ಬಂಡಪೈನಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 53,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_053",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Hurugalu, Satinwood",
    "scientificName": "Chloroxylon swietinia",
    "kannadaName": "ಬಿತ್ತುಲ, ಹರಗಿಳು, ಹುರಿಹುಳಿ, ಮಸುಲ, ಹುರುಗಲು, ಸಾಟಿನ್ ಮರ",
    "ratePerCubicMeter": 11779,
    "category": "",
    "displayOrder": 54,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_054",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Pali, Hadasalu",
    "scientificName": "Palaquium ellipticum",
    "kannadaName": "ಪಂಚೋಂತಾ, ಪಾಲಿ, ಹಡಸಾಲು",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 55,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_055",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Rudraksha, Sattaga",
    "scientificName": "Elaeocarpus tuberculatus",
    "kannadaName": "ದಂಡೆ ಮರ, ಭೂತಾಳಿ ದಂಡಲೆ, ರುದ್ರಾಕ್ಷ, ಸತ್ತಗ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 56,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_056",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Godda",
    "scientificName": "Garuga pinnata",
    "kannadaName": "ಗೊದ್ದನಮರ, ಗೊಡ್ಡ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 57,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_057",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Enne mara",
    "scientificName": "Kingiodendron pinnatum",
    "kannadaName": "ಎಣ್ಣೆ ಮರ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 58,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_058",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Holegeri",
    "scientificName": "Holigarna arnottiana",
    "kannadaName": "ಹೊಲಗೇರು",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 59,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_059",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Halga, Kabri",
    "scientificName": "Hopea wightiana",
    "kannadaName": "ಹೈಗಾ, ಕಲ್ಲೇವು, ಹಲು, ಕಬ್ರಿ",
    "ratePerCubicMeter": 9362,
    "category": "",
    "displayOrder": 60,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_060",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Doddathoppe",
    "scientificName": "Hymenodictyon excelsum",
    "kannadaName": "ದೊಡ್ಡ ಮರ, ದಿಡ್ಡಿಮರ, ದೊಡ್ಡತೊಪ್ಪೆ",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 61,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_061",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Gulmavu, Kulimavu",
    "scientificName": "Persea macarantha",
    "kannadaName": "ಗುಳಮಾವು, ಕುಳಿಶಾವು",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 62,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_062",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Mavu, Mango",
    "scientificName": "Mangifera indica",
    "kannadaName": "ಮಾವು ಮ್ಯಾಂಗೋ",
    "ratePerCubicMeter": 9362,
    "category": "",
    "displayOrder": 63,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_063",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bevu, Neem, Margosa",
    "scientificName": "Melia dubia",
    "kannadaName": "ಹೆಬ್ಬೇವು, ನೀಮ್, ಮಾರ್ಗೋಸಾ",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 64,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_064",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Sampige, Champak, Kolasampige",
    "scientificName": "Michelia champaca",
    "kannadaName": "ಸಂಪಿಗೆ, ಚಂಪಕ, ಕೋಲಸಂಪಿಗೆ",
    "ratePerCubicMeter": 11326,
    "category": "",
    "displayOrder": 65,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_065",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kendala, Sagade, Kusum, Purka",
    "scientificName": "Schleichera trijuga - S. oleosa",
    "kannadaName": "ಕುಸುಮ ಮರ, ಕೆಂಡಲ, ಸಗಡೆ, ಕುಸುಮ್, ಪುರ್ಕ",
    "ratePerCubicMeter": 12081,
    "category": "",
    "displayOrder": 66,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_066",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Doddamete, Ambod, Radembale",
    "scientificName": "Spondias acuminata",
    "kannadaName": "ಆಮ್ಟೆ, ದೊಡ್ಡ ಮೇಟೆ, ಅಂಬೋಡ್, ರಡೆಂಬಲೆ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 67,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_067",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Amate",
    "scientificName": "Spondias mangifera",
    "kannadaName": "ಅಂಬಟೆ, ಅಮಟೆ",
    "ratePerCubicMeter": 7550,
    "category": "",
    "displayOrder": 68,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_068",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Genasu",
    "scientificName": "Stereospermum xylocarpum",
    "kannadaName": "ಪಾದರಿ, ಗೆಣಸು",
    "ratePerCubicMeter": 8607,
    "category": "",
    "displayOrder": 69,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_069",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kajari, Kasaka, Marking nut",
    "scientificName": "Strychnos nuxvomica",
    "kannadaName": "ಕಜರಿ, ಕಸಕ, ಮಾರ್ಕಿಂಗ್ ಬೀಜ",
    "ratePerCubicMeter": 8607,
    "category": "",
    "displayOrder": 70,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_070",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Holematti, Thoremathi, Bilimathi",
    "scientificName": "Terminalia arjuna",
    "kannadaName": "ಹೊಳೆಮತ್ತಿ, ತೊರೆಮತ್ತಿ, ಬಿಳಿಮತ್ತಿ",
    "ratePerCubicMeter": 8607,
    "category": "",
    "displayOrder": 71,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_071",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Hale, Galnut, Harada, Myrobolan",
    "scientificName": "Terminalia chebula",
    "kannadaName": "ಅಳಲೆಕಾಯಿ, ಹಾಳೆ, ಗಾಲ್ನಟ್, ಹರದ, ಮ್ಯರೋಬೋಲಾನ್",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 72,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_072",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Jemal, Chenni, Bondale, Maine, Bolur",
    "scientificName": "Tetrameles nudiflora",
    "kannadaName":
        "ಕಾಡು ಬೆಂಡೆ, ಬೋಳಾರ್, ಜೆಮಾಲ್, ಚೆನ್ನಿ, ಬೊಂಡಲೆ, ಮನ್ನೆ, ಬೋಲುರ್, ಜೇವಾಲ್",
    "ratePerCubicMeter": 9362,
    "category": "",
    "displayOrder": 73,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_073",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Jali, Karijali",
    "scientificName": "Acacia nilotica",
    "kannadaName": "ಜಾಲಿ, ಕರಿಜಾಲಿ",
    "ratePerCubicMeter": 11779,
    "category": "",
    "displayOrder": 74,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_074",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Manjuti",
    "scientificName": "Adenanthera pavinia",
    "kannadaName": "ಆನಗುಲಗಂಜಿ, ಮಂಜಾಡಿ, ಮಂಜುಟಿ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 75,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_075",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Halmaddi",
    "scientificName": "Ailanthus malabaricum",
    "kannadaName": "ಬಗಧೂಪ, ಮದ್ದಿಧೂಪ, ಹಾಲ್ಮಡ್ಡಿ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 76,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_076",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Tottile",
    "scientificName": "Aglaia lawii",
    "kannadaName": "ಕಾರಗಿಲ್, ಮುದ್ದಸದ, ತೊಟ್ಟಿಲೆ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 77,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_077",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Jasund, Chandul",
    "scientificName": "Antiaris toxicaria",
    "kannadaName": "ಅರಣ್ಯ ಪಟೆ, ಅಜ್ಜನ ಪಟೆ, ಜಸುಂಡ್ ಚಂದುಲ್",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 78,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_078",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Basavanapada",
    "scientificName": "Bauhinia reticulata",
    "kannadaName": "ಕುಂಚವಾಳ, ಬಸವನಪಾದ",
    "ratePerCubicMeter": 8003,
    "category": "",
    "displayOrder": 79,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_079",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Neeli, Govarnelu, Nira, Thinpu",
    "scientificName": "Bischofia javanica",
    "kannadaName": "ಗೋವದಣೆ, ನೀಲಿಮರ, ಗೋವಿನೇಲು ನೀರ ತಿರುಪು, ಗೊಬ್ಬುನೇರಳೆ",
    "ratePerCubicMeter": 8003,
    "category": "",
    "displayOrder": 80,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_080",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Murukali, Nurkal, Chironjee",
    "scientificName": "Buchanania latifolia",
    "kannadaName": "ಮುರಕಳಿ, ನುರ್ಕಲ್, ಚಿರೋಂಜಿ, ಕೊಳೆಗೇರು",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 81,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_081",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Punchi",
    "scientificName": "Carallia integerrima",
    "kannadaName": "ಅಂಡಿಮುರುಗಲು, ಅಂಡಿಪುನಾರು, ಪುಂಚಿ",
    "ratePerCubicMeter": 8456,
    "category": "",
    "displayOrder": 82,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_082",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Karigarane",
    "scientificName": "Celestrus species",
    "kannadaName": "ಬಿಟರ್ನೆಟ್, ಸಿಬಿಂದಿ ಬಳ್ಳಿ, ಕರಂಗಣೆ",
    "ratePerCubicMeter": 8456,
    "category": "",
    "displayOrder": 83,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_083",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "dalchini",
    "scientificName": "Cinnaomum verum",
    "kannadaName": "ದಾಲ್ಚಿನ್ನಿ, ಲವಂಗಪಟ್ಟೆ",
    "ratePerCubicMeter": 8456,
    "category": "",
    "displayOrder": 84,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_084",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Nalkordsha",
    "scientificName": "Cleistanthus collnius",
    "kannadaName": "ಕಡಿಸೆ, ನಾಲ್ಕೊಡಪಾ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 85,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_085",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kanagalu, Kolategu, Malageji",
    "scientificName": "Dillenia pentagyna",
    "kannadaName": "ಕಾಡು ಕನಗಲು, ಕೋಲಟೆಗು, ಮಳಗೇರು",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 86,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_086",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Chorkali",
    "scientificName": "Dispyros microphylla",
    "kannadaName": "ಕಂಚಿಗನಮರ, ಹೊಳೆಮತ್ತಿ, ತೊರೆಮತ್ತಿ, ಬಿಳಿಮತ್ತಿ",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 87,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_087",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Hongara, Panvala",
    "scientificName": "Erythrina indica",
    "kannadaName": "ಹಾರಿವಾಳ, ಹೊಂಗರ, ಪನ್ವಾಲ, ಮುಳ್ಳುಮುರಿಗೆ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 88,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_088",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Chikkani",
    "scientificName": "Eugenia gardneri",
    "kannadaName": "ಬಿಳಿತಿರುಪು, ಚಿಕ್ಕಾಣಿ",
    "ratePerCubicMeter": 8456,
    "category": "",
    "displayOrder": 89,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_089",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Adavi atthi",
    "scientificName": "Ficus exasperata",
    "kannadaName": "ಅಡವಿ ಅತ್ತಿ, ಗರಗತ್ತಿ",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 90,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_090",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Atthi",
    "scientificName": "Ficus racemosa",
    "kannadaName": "ಅತ್ತಿಮರ, ಅರಳಿಮರ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 91,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_091",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Neer atthi",
    "scientificName": "Ficus nervosa",
    "kannadaName": "ಕರಬಸರಿ, ನೀರ್ ಹತ್ತಿ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 92,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_092",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bilibasari",
    "scientificName": "Ficus tsiela",
    "kannadaName": "ಬೋವಿ, ಬಿಳಿಬಸರಿ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 93,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_093",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Attak, Hennusampige",
    "scientificName": "Flacourtia montana",
    "kannadaName": "ಅಟ್ಟಕ್, ಹೆಣ್ಣುಸಂಪಿಗೆ",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 94,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_094",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Uppage, Aradaia",
    "scientificName": "Garcinia cambogia",
    "kannadaName": "ಉಪ್ಪಗೆ, ಕಟಾಂಪುಲಿ, ಆರಾಡಿಯಾ",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 95,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_095",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Silver oak, Vellangi",
    "scientificName": "Grevillea robusta",
    "kannadaName": "ಸಿಲ್ವರ್ ಓಕ್, ವೆಲ್ಲಂಗಿ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 96,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_096",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kadubende",
    "scientificName": "Gyrocarpus americanus",
    "kannadaName": "ಕಾಡುಬೆಂಡೆ, ಪೋಲಿಕ",
    "ratePerCubicMeter": 8456,
    "category": "",
    "displayOrder": 97,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_097",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Holoptelia beddomei",
    "scientificName": "Holoptelia beddomei",
    "kannadaName": "ರಸಬೀಜ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 98,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_098",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Thapasi, Kaladri, Kanju",
    "scientificName": "Holoptelia integrifolia",
    "kannadaName": "ತಪಸಿ, ಕಾಲಾದ್ರಿ ಕಂಜು, ತಪಸಿಮರ",
    "ratePerCubicMeter": 8456,
    "category": "",
    "displayOrder": 99,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_099",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Belaga, Bende",
    "scientificName": "Kydia calycina",
    "kannadaName": "ಬೆಮ್ಮ, ಕೋಳಿಬೆಂಡೆ, ಬೆಳಗ, ಬೆಂಡೆ",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 100,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_100",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Holedasavala",
    "scientificName": "Lagerstroemia speciosa",
    "kannadaName": "ಹೊಳೆದಾಸವಾಳ",
    "ratePerCubicMeter": 9060,
    "category": "",
    "displayOrder": 101,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_101",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Channangi",
    "scientificName": "Lagerstroemia parviflora",
    "kannadaName": "ಚನ್ನಂಗಿ, ವೆಂಟಾಸಿ",
    "ratePerCubicMeter": 9967,
    "category": "",
    "displayOrder": 102,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_102",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Gojjal, Arenelli",
    "scientificName": "Lannea grandis",
    "kannadaName": "ಗೊಡ್ಡ, ಕುರುಟಿಗೆ, ಗುಂಪಿನ, ಉದಿಮರ, ಗೊಜ್ಜಲ್, ಅರನವಲ್ಲಿ",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 103,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_103",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Punisi, Punygam",
    "scientificName": "Linociera malabarica",
    "kannadaName": "ಹರದಾಗ, ಮುದ್ದೋದಲೆ, ಮ್ಯಸಾಳೆ, ಪುನಿಸಿ, ಪುನಿಗಮ್",
    "ratePerCubicMeter": 8154,
    "category": "",
    "displayOrder": 104,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_104",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Sonnalppe, Ippe",
    "scientificName": "Madhuca latifolia",
    "kannadaName": "ಕಾಡು ಇಪ್ಪೆ, ಸೋನ್ನಲ್ಲೆ, ಇಪ್ಪೆ",
    "ratePerCubicMeter": 7550,
    "category": "",
    "displayOrder": 105,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_105",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Gulla",
    "scientificName": "Mastixia arborea",
    "kannadaName": "ಮಾಸ್ಟಿಕ್ಸಿಯಾ, ಗುಲ್ಲಾ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 106,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_106",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kadujati",
    "scientificName":
        "Miscellaneous species not finding mention anywhere in the list of timbers above and below, to be referred to as 'Junglewood' as per PCCF(HoFF) Circular number B3/Sales/Billets/CR-18/2015-16 dated 06th January 2017",
    "kannadaName": "ಕಾಡುಜಾತಿ",
    "ratePerCubicMeter": 10571,
    "category": "",
    "displayOrder": 107,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_107",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Ramanadike",
    "scientificName": "Myristica magnifica",
    "kannadaName": "ರಾಮಪತ್ರೆ, ಜಾಯಿಕಾಯಿ, ರಾಮನಾಡಿಕೆ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 108,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_108",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Ramapathre",
    "scientificName": "Myristica malabarica",
    "kannadaName": "ಕಟ್ಟುಜಾತಿ, ಕನಾಗಿ, ದೊಡ್ಡಜಾಜಿಕಾಯಿ, ರಾಮನಾಡಿಕೆ, ರಾಮಪತ್ರೆ",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 109,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_109",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Asoka",
    "scientificName": "Saraca asoca",
    "kannadaName": "ಅಚರಗೆ, ಅಚರಂಗ, ಅಶೋಕ್",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 110,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_110",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Honge",
    "scientificName": "Milletia pinnata",
    "kannadaName": "ಹೊಂಗೆ ಮರ",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 111,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_111",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Polavu, Thopa",
    "scientificName": "Pterospermum heyneanum",
    "kannadaName": "ರಾಜತರು, ಕನಕ, ಚಂಪಕ, ಪೊಲವು, ತೋಪ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 112,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_112",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Obalu, Kaladri, Karihessare",
    "scientificName": "Saccopetalum tomentosum (Miliusa tomentosa)",
    "kannadaName": "ಕರಿಹೆಸ್ಸರೆ, ಹಸರು, ಓಬಲು, ಕಾಲಾದ್ರಿ, ಕರಿಹೆಸ್ಸರೆ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 113,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_113",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Soapnut, Untuwala",
    "scientificName": "Sapindus emarginatus",
    "kannadaName": "ಸಾಬೂನು ಕಾಯಿ, ಅಂಟುವಾಳ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 114,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_114",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kolgotee, Savige",
    "scientificName": "Schrebera sweiteioides",
    "kannadaName": "ಬುಲಾ, ಕಲ್ಗೊಟೆ, ಮೊಗಲಿಂಗ, ಮೊಗರಾಮರಾಮ್, ಕೋಲೋಟಿ ಸಾವಿಗೆ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 115,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_115",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Geru, Cashew nut",
    "scientificName": "Semicarpus anacardium",
    "kannadaName": "ಗುಡ್ಡಗೇರು, ಕರಿಗೇರು, ಗೇರು, ಗೋಡಂಬಿ ಬೀಜ",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 116,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_116",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Savni, Some, Kalgarige",
    "scientificName": "Soymida febrifuga",
    "kannadaName": "ಸೋಮೆ ಸಮ್, ಕೆಮ್ಮರ, ಸಾವ್ನಿ, ಸೋಮಿ, ಕಳಗಿನೆ",
    "ratePerCubicMeter": 8305,
    "category": "",
    "displayOrder": 117,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_117",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Kaithali",
    "scientificName": "Sterculia alata",
    "kannadaName": "ಕೋಲುಗಿಡ, ತಟ್ಟೆಲೆ ಮರ, ಕೈತಳೆ",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 118,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_118",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Udi, Kadalu",
    "scientificName": "Stereospermum chelnoides",
    "kannadaName": "ಆದರಿ, ಬಿಳಿಪಾದರಿ, ಹಾದರಿ, ಹುದಿ, ಪುರಳಿ, ಕಡಲು",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 119,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_119",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Bilinaru, Savige",
    "scientificName": "Stereospermum villosa",
    "kannadaName": "ಕಲಾದ್ರಿ, ಕಲ್ಲುದರೆ, ಪಡ್ಡಿ, ಮಲ್ಲರಿ, ಬಿಳಿನಾರು, ಸವಿಗೆ",
    "ratePerCubicMeter": 8909,
    "category": "",
    "displayOrder": 120,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_120",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Tare, Ghoting, Shanthi",
    "scientificName": "Terminalia bellerica",
    "kannadaName": "ತಾರೆಕಾಯಿ, ಗೋಟಿಂಗ್, ಶಾಂತಿ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 121,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_121",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Badam, Bange, Taree",
    "scientificName": "Terminalia catapa",
    "kannadaName": "ಕಾಡು ಬಾದಾಮಿ, ನಾಟಿ ಬಾದಾಮಿ, ಬಾದಾಮ್, ಬಾಂಗೆ, ತಾರಿ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 122,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_122",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
  {
    "masterType": "Species",
    "value": "Katumbla",
    "scientificName": "Trewia nudiflora",
    "kannadaName": "ಅತ್ತರಸು, ಕಾಟುಂಬ್ಲಾ",
    "ratePerCubicMeter": 7852,
    "category": "",
    "displayOrder": 123,
    "speciesGroup": "TIMBER",
    "code": "TIMBER_2026_123",
    "parentCode": "",
    "remarks": "",
    "isActive": 1,
  },
];
